from distutils.core import setup
setup(
  name = 'bc-device',
  packages = ['behaviorcloud.device'],
  version = '0.1.1',
  license='MIT',
  description = 'A package to create a BehaviorCloud compatible device firmware.',
  author = 'Derek Edwards',
  author_email = 'derek@behaviorcloud.com',
  url = 'https://github.com/behaviorcloud/bc-device-py',
  download_url = 'https://github.com/behaviorcloud/bc-device-py/archive/v0.1.1.tar.gz',
  keywords = ['behaviorcloud', 'behavior', 'cloud', 'device', 'data', 'daemon', 'api'],
  install_requires=[
    'python-dateutil',
    'requests',
    'sentry-sdk',
    'paho-mqtt',
  ],
  classifiers=[
    'Development Status :: 3 - Alpha',
    'Intended Audience :: Developers',
    'Topic :: Software Development :: Build Tools',
    'License :: OSI Approved :: MIT License',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.4',
    'Programming Language :: Python :: 3.5',
    'Programming Language :: Python :: 3.6',
    'Programming Language :: Python :: 3.7',
  ],
)